
- hosts: devchain
  remote_user: root
  tasks: 

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    - name: Install dirmngr and https transport
      apt:
        name: 
          - dirmngr
          - apt-transport-https
        state: present

    - name: Add nodejs key
      apt_key:
        keyserver: keys.gnupg.net
        id: "1655A0AB68576280"

    - name: Add NodeJS Repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_10.x stretch main
        state: present

    - name: Install required debs
      apt:
        name: 
          - nodejs
          - git
          - build-essential
        state: present

    - name: Download parity
      get_url:
        url: https://releases.parity.io/ethereum/v2.2.5/x86_64-unknown-linux-gnu/parity
        dest: /usr/local/bin/parity
        mode: "0755"
        force: yes

    - name: Create /etc/parity
      file: 
        path: /etc/parity
        state: directory
        mode: "0755"

    - name: Create /var/spool/parity
      file: 
        path: /var/spool/parity
        state: directory
        mode: "0755"

    - name: Install devchain.json
      template:
        src: files/devchain.json
        dest: /etc/parity/devchain.json

    - name: Install devchain.service
      template:
        src: files/devchain.service
        dest: /lib/systemd/system/devchain.service

    - name: Start devchain
      systemd:
        name: devchain
        daemon-reload: true
        state: restarted

    - name: Clone etherchain-light
      git:
        repo: "https://github.com/lbthomsen/etherchain-light.git"
        dest: /root/etherchain-light
        recursive: true

    - name: Run npm install
      shell: npm install
      args:
        chdir: /root/etherchain-light

    - name: Copy etherchain-light config
      template:
        src: files/config.js
        dest: /root/etherchain-light/config.js

    - name: Copy etherchain.service
      template: 
        src: files/etherchain.service
        dest: /lib/systemd/system/etherchain.service

    - name: Restart etherchain
      systemd:
        name: etherchain
        daemon-reload: true
        state: restarted
